### ISSUE TITLE
Tests: assertNotEqual for get_invalid_rentable?

### ISSUE THREAD

**Issue by bipol** [airn/Rentr#6]
WTF IS THIS BULLSHIT

**Comment by airn** [comment]
I don't know why that is there.

**Comment by airn** [comment]
So i changed the assertion but it fails now. I don't understand why, the store invalid test case is is passing and is the exact same code... The only thing I could see is since the rentables aren't getting deleted after every test there is one for the pk we are passing it since it is returning a 200. I did try and make the pk 900000000000 and i still got a 200.
